# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-full:latest

#image:
#    file: .gitpod.Dockerfile

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: | # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
      JAVA="18.0.1.fx-zulu"
      echo "n" | sdk install java ${JAVA} || true
      sdk default java ${JAVA}
    command: |
      git clone https://github.com/dylibso/chicory.git
      cd chicory
      cd test-gen-plugin
      mvn clean package
      cd ..
      mvn clean package
      cp runtime/target/runtime-*.jar ../Hello/src/main/resources
      cd ../Hello
      mvn install:install-file \
        -Dfile=/workspace/arhuaco/Hello/src/main/resources/runtime-1.0-SNAPSHOT.jar \
        -DgroupId=com.dylibso.chicory \
        -DartifactId=chicory \
        -Dversion=0.0.1 \
        -Dpackaging=jar \
        -DgeneratePom=true


# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
