# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-full:latest

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: | # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
      #git clone https://github.com/dylibso/chicory.git
      #cd chicory
      #sdk install java 18.0.1.fx-zulu -y
      #sdk default java 18.0.1.fx-zulu
      #mvn clean package

    command: |
      echo "🚧"


# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
